{% set version = "2021.8.2" %}

package:
  name: adlfs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/adlfs/adlfs-{{ version }}.tar.gz
  sha256: 7fcbc183e054a6f50045fdef9ca77e3b6cf104e6670d81e8e44c48608918d190

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >3.6
    - pip
  run:
    - python >3.6
    - aiohttp
    - azure-core >=1.7.0
    - azure-datalake-store >=0.0.46,<0.1
    - azure-identity
    - azure-storage-blob >=12.5.0
    - fsspec >=2021.6.1

test:
  imports:
    - adlfs
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/dask/adlfs
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: fsspec-compatible Azure Datalake and Azure Blob Storage access

extra:
  recipe-maintainers:
    - hayesgb
    - martindurant
    - TomAugspurger
    - raybellwaves
    - dhirschfeld
