{% set version = "0.3.2" %}

package:
  name: adlfs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/adlfs/adlfs-{{ version }}.tar.gz
  sha256: 8a8518f771c5c9684f39206a764d50fd15991ad46e6703ebe2a36ca3c115fb54

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - azure-core >=1.5.0
    - azure-datalake-store >=0.0.46,<0.1
    - azure-identity
    - azure-storage-blob >=12.0.0
    - fsspec >=0.6.0,<0.8
    - msrestazure

test:
  imports:
    - adlfs
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/dask/adlfs
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: fsspec-compatible Azure Datalake and Azure Blob Storage access

extra:
  recipe-maintainers:
    - hayesgb
    - martindurant
    - raybellwaves
