{% set version = "2024.2.0" %}

package:
  name: adlfs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/adlfs/adlfs-{{ version }}.tar.gz
  sha256: 860f5ddbd7f3c2553d84a101717dc5736e823305e0d51e8c0058bc85a7fa304d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8,<3.12
    - pip
  run:
    - python >=3.8
    - aiohttp >=3.7.0
    - azure-core >=1.23.1,<2.0.0
    - azure-datalake-store >=0.0.46,<0.1
    - azure-identity
    - azure-storage-blob >=12.12.0
    - fsspec >=2023.12.0

test:
  imports:
    - adlfs

about:
  home: https://github.com/dask/adlfs
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: fsspec-compatible Azure Datalake and Azure Blob Storage access

extra:
  recipe-maintainers:
    - hayesgb
    - martindurant
    - TomAugspurger
    - raybellwaves
    - dhirschfeld
