{% set version = "0.5.3" %}

package:
  name: adlfs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/adlfs/adlfs-{{ version }}.tar.gz
  sha256: da988bad3c8dc0fab015fee6863dd47721857ef6008703d9e8dc60b1a65fe53a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - aiohttp  
    - azure-core >=1.5.0
    - azure-datalake-store >=0.0.46,<0.1
    - azure-identity
    - azure-storage-blob >=12.5.0
    - fsspec >=0.8.0  
    - msrestazure

test:
  imports:
    - adlfs
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/dask/adlfs
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: fsspec-compatible Azure Datalake and Azure Blob Storage access

extra:
  recipe-maintainers:
    - hayesgb
    - martindurant
    - raybellwaves
